[HOTFIX] Updating pytest dependency to fix error
It was discovered in builds from https://github.com/alan-turing-institute/dodo/pull/79
and https://github.com/alan-turing-institute/dodo/pull/78 a failure has occurred on Travis

Command:
    $ pytest -rs --ignore=./tests/integration ./tests

Error:
    TypeError: attrib() got an unexpected keyword argument 'convert'

It appears that pytest seems to have the package attrs as a dependency.

REF:
    https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert

    modified:   requirements.txt

[SQUASH] Moving pytest bump to requirements-dev instead

Since pytest is only a requirement for development, it should reside in
'requirements-dev.txt' file instead of the main 'requirements.txt' file
	modified:   requirements-dev.txt
	modified:   requirements.txt